const seedUsers=[{name:'عبدالرحمن',role:'rep'},{name:'سعد',role:'rep'},{name:'خليل',role:'rep'}];
const seedCustomers=[{company:'شركة النور التجارية',person:'أحمد السالم',rep:'عبدالرحمن',note:'تم التواصل مع العميل',status:'نشط',next:'2026-09-10'},{company:'مؤسسة الخليج',person:'خالد العتيبي',rep:'سعد',note:'بانتظار تحديد موعد',status:'قيد المتابعة',next:'2026-09-11'},{company:'شركة الأفق',person:'سارة أحمد',rep:'خليل',note:'تم إرسال العرض',status:'معلق',next:'2026-09-12'}];
let users=JSON.parse(localStorage.getItem('psh_users')||'null')||seedUsers;
let customers=JSON.parse(localStorage.getItem('psh_customers')||'null')||seedCustomers;
let app=document.getElementById('app');
function persist(){localStorage.setItem('psh_users',JSON.stringify(users));localStorage.setItem('psh_customers',JSON.stringify(customers))}
function layout(body,user){app.innerHTML=`<div class="shell"><header class="top"><div class="brand">PayScale Hub<small>Sales Tracker</small></div><div class="user">${user||''}</div></header><section class="content">${body}</section></div>`}
function login(){app.innerHTML=`<div class="login"><div class="brand">PayScale Hub<small>Sales Tracker</small></div><h1>اختر المستخدم</h1><p class="note">الدخول إلى متابعة العملاء وفرص المبيعات</p><div class="names">${users.map(u=>`<button class="name" onclick="enter('${u.name}')">${u.name}</button>`).join('')}<button class="name" onclick="managerLogin()">مدير المبيعات</button></div></div>`}
function enter(name){const rows=customers.filter(x=>x.rep===name);layout(`<div class="hero"><div><h1>صفحة المندوب</h1><p>مرحبًا ${name}، تابع عملاءك ومهامك القادمة.</p></div><button class="primary" onclick="showAddCustomer('${name}')">إضافة عميل</button></div><div class="cards"><div class="card"><span>عملائي</span><strong>${rows.length}</strong></div><div class="card"><span>المتابعات القادمة</span><strong>${rows.filter(x=>x.next).length}</strong></div><div class="card"><span>الزيارات هذا الشهر</span><strong>3</strong></div></div><div class="panel"><h2>عملائي</h2><table><thead><tr><th>اسم العميل</th><th>الشخص المسؤول</th><th>رقم الهاتف</th><th>آخر ملاحظة</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.company}</td><td>${r.person}</td><td>${r.phone||'—'}</td><td class="note">${r.note||'—'}</td><td><span class="status">${r.status}</span></td><td><button class="ghost" onclick="showAddFollowup('${r.company}','${name}')">إضافة متابعة</button></td></tr>`).join('')}</tbody></table></div>`,name)}
function managerLogin(){app.innerHTML=`<div class="login"><div class="brand">PayScale Hub</div><h1>مدير المبيعات</h1><input id="pass" type="password" placeholder="كلمة المرور" style="padding:12px;border:1px solid var(--line);border-radius:8px;font-family:inherit"><br><br><button class="primary" onclick="checkManager()">دخول</button></div>`}
function checkManager(){if(document.getElementById('pass').value==='2026')manager();else alert('كلمة المرور غير صحيحة')}
function manager(){layout(`<div class="hero"><div><h1>مدير المبيعات</h1><p>متابعة العملاء والفرص لجميع المندوبين.</p></div><button class="primary" onclick="showAddRep()">إضافة مندوب جديد</button></div><div class="cards"><div class="card"><span>إجمالي العملاء</span><strong>${customers.length}</strong></div><div class="card"><span>المتابعات القادمة</span><strong>${customers.filter(x=>x.next).length}</strong></div><div class="card"><span>المندوبون</span><strong>${users.length}</strong></div></div><div class="panel"><h2>المندوبون والعملاء والمتابعات</h2><table><thead><tr><th>المندوب</th><th>العميل</th><th>الشخص المسؤول</th><th>رقم الهاتف</th><th>الحالة</th><th>آخر ملاحظة</th></tr></thead><tbody>${customers.map(r=>`<tr><td>${r.rep}</td><td>${r.company}</td><td>${r.person}</td><td>${r.phone||'—'}</td><td><span class="status">${r.status}</span></td><td class="note">${r.note||'—'}</td></tr>`).join('')}</tbody></table></div>`,'مدير المبيعات')}
function modal(title,fields,submit){app.insertAdjacentHTML('beforeend',`<div class="modal"><div class="modal-box"><h2>${title}</h2>${fields}<div class="actions"><button class="primary" onclick="${submit}">حفظ</button><button class="ghost" onclick="this.closest('.modal').remove()">إلغاء</button></div></div></div>`)}
function showAddCustomer(rep){modal('إضافة عميل جديد',`<label>اسم العميل<input id="cCompany"></label><label>اسم الشخص المسؤول<input id="cPerson"></label><label>رقم الهاتف<input id="cPhone" type="tel"></label>`,`addCustomer('${rep}')`)}
function addCustomer(rep){const company=document.getElementById('cCompany').value.trim(),person=document.getElementById('cPerson').value.trim(),phone=document.getElementById('cPhone').value.trim();if(!company||!person||!phone)return alert('يرجى تعبئة الحقول الثلاثة');customers.push({company,person,phone,rep,note:'عميل جديد',status:'جديد',next:''});persist();document.querySelector('.modal').remove();enter(rep)}
function showAddFollowup(company,rep){modal('إضافة متابعة',`<p class="note">العميل: ${company}</p><label>نوع المتابعة<select id="fType"><option>اتصال</option><option>واتساب</option><option>اجتماع</option><option>زيارة</option></select></label><label>تاريخ المتابعة القادمة<input id="fNext" type="date"></label><label>ملخص المتابعة<textarea id="fNote"></textarea></label>`,`addFollowup('${company}','${rep}')`)}
function addFollowup(company,rep){const note=document.getElementById('fNote').value.trim();if(!note)return alert('اكتب ملخص المتابعة');const c=customers.find(x=>x.company===company&&x.rep===rep);if(c){c.note=note;c.next=document.getElementById('fNext').value;c.status='قيد المتابعة'}persist();document.querySelector('.modal').remove();enter(rep)}
function showAddRep(){modal('إضافة مندوب جديد',`<label>اسم المندوب<input id="newRep"></label>`,`addRep()`)}
function addRep(){const n=document.getElementById('newRep').value.trim();if(!n)return alert('اكتب اسم المندوب');if(users.some(x=>x.name===n))return alert('المندوب موجود مسبقًا');users.push({name:n,role:'rep'});persist();document.querySelector('.modal').remove();manager()}
login();
