const API_URL='https://script.google.com/macros/s/AKfycbyapKP8_yN5rfrRmrXYGamE9Kv-ro55iJh3Q4Mb635eeCqDEcT9DKLRkDVOLOWNn-3rmQ/exec';
const seedUsers=[{name:'عبدالرحمن',role:'rep'},{name:'سعد',role:'rep'},{name:'خليل',role:'rep'}];
const seedCustomers=[{company:'شركة النور التجارية',person:'أحمد السالم',phone:'0501234567',rep:'عبدالرحمن',note:'تم التواصل مع العميل',status:'شركة محتملة',followDate:'2026-09-07',nextVisit:'2026-09-10',visits:[]},{company:'مؤسسة الخليج',person:'خالد العتيبي',phone:'0509876543',rep:'سعد',note:'بانتظار تحديد موعد',status:'شركة محتملة',followDate:'2026-09-07',nextVisit:'2026-09-08',visits:[]},{company:'شركة الأفق',person:'سارة أحمد',phone:'0551112233',rep:'خليل',note:'تم إرسال العرض',status:'تم الشراء',followDate:'2026-09-06',nextVisit:'2026-09-09',visits:[]}];
let users=JSON.parse(localStorage.getItem('psh_users')||'null')||seedUsers;let customers=JSON.parse(localStorage.getItem('psh_customers')||'null')||seedCustomers;let app=document.getElementById('app');
const today=()=>new Date().toISOString().slice(0,10);const tomorrow=()=>{let d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)};const fmt=d=>d?new Date(d+'T00:00:00').toLocaleDateString('ar-SA'): '—';
async function loadData(){try{const r=await fetch(API_URL);const d=await r.json();if(d.ok&&Array.isArray(d.customers)){customers=d.customers.map(x=>({company:x[1],person:x[2],phone:x[3],rep:x[4],status:x[5]||'شركة محتملة',note:x[6]||'',followDate:x[7]||'',nextVisit:'',visits:[]}));}}catch(e){console.warn('API unavailable',e)}login()}

async function apiPost(payload){try{await fetch(API_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify(payload)})}catch(e){console.warn('Save failed',e)}}
function persist(){localStorage.setItem('psh_users',JSON.stringify(users));localStorage.setItem('psh_customers',JSON.stringify(customers))}
function layout(body,user){app.innerHTML=`<div class="shell"><header class="top"><div class="brand">PayScale Hub<small>Sales Tracker</small></div><div class="user">${user||''}</div></header><section class="content">${body}</section></div>`}
function login(){app.innerHTML="<div class=\"login\"><div class=\"brand\">PayScale Hub<small>Sales Tracker</small></div><h1>اختر المستخدم</h1><p class=\"note\">الدخول إلى متابعة العملاء وفرص المبيعات</p><div class=\"manager-access\"><button class=\"manager-card\" onclick=\"managerLogin()\"><span>مدير المبيعات</span><small>لوحة الإدارة والتقارير</small></button></div><div class=\"reps-section\"><div class=\"section-label\">المندوبون</div><div class=\"reps-grid\">"+users.map(u=>"<button class=\"rep-card\" onclick=\"enter('"+u.name+"')\">"+u.name+"</button>").join("")+"</div></div></div>"}
function statusBadge(s){return `<span class="status ${s==='تم الشراء'?'done':s==='تم الاتفاق على الشراء'?'converted':''}">${s}</span>`}
function repCards(rows){return `<div class="cards"><div class="card card-blue"><span>الشركات المحتملة</span><strong>${rows.filter(x=>x.status==='شركة محتملة').length}</strong></div><div class="card card-green"><span>المتابعات القادمة</span><strong>${rows.filter(x=>x.nextVisit).length}</strong></div><div class="card card-purple"><span>تم الشراء</span><strong>${rows.filter(x=>x.status==='تم الشراء').length}</strong></div></div>`}
function enter(name){const rows=customers.filter(x=>x.rep===name);layout(`<div class="hero"><div><h1>صفحة المندوب</h1><p>مرحبًا ${name}، تابع عملاءك ومهامك القادمة.</p></div><button class="primary" onclick="showAddCustomer('${name}')">إضافة عميل</button></div>${repCards(rows)}<div class="panel"><h2>الشركات المحتملة</h2><table><thead><tr><th>اسم العميل</th><th>الشخص المسؤول</th><th>رقم الهاتف</th><th>الحالة</th><th>آخر ملاحظة</th><th>إجراء</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${r.company}</td><td>${r.person}</td><td>${r.phone||'—'}</td><td>${statusBadge(r.status)}</td><td class="note">${r.note||'—'}</td><td><button class="ghost" onclick="showAddFollowup('${r.company}','${name}')">إضافة متابعة</button> <button class="ghost" onclick="showHistory('${r.company}','${name}')">سجل المتابعات</button></td></tr>`).join('')}</tbody></table></div>`,name)}
function managerLogin(){app.innerHTML=`<div class="login"><div class="brand">PayScale Hub</div><h1>مدير المبيعات</h1><input id="pass" type="password" placeholder="كلمة المرور" style="padding:12px;border:1px solid var(--line);border-radius:8px;font-family:inherit"><br><br><button class="primary" onclick="checkManager()">دخول</button></div>`}
function checkManager(){if(document.getElementById('pass').value==='2026')manager();else alert('كلمة المرور غير صحيحة')}
function visitsBox(){const v=customers.filter(x=>x.nextVisit===today()||x.nextVisit===tomorrow());return `<div class="panel visits-panel"><h2>سجل الزيارات المنسقة</h2><div class="visit-list">${v.length?v.map(x=>`<div class="visit-row"><b>${fmt(x.nextVisit)}</b><span>${x.company}</span><small>${x.rep}</small></div>`).join(''):'لا توجد زيارات اليوم أو غدًا'}</div></div>`}
function manager(){layout(`<div class="hero"><div><h1>مدير المبيعات</h1><p>متابعة العملاء والفرص لجميع المندوبين.</p></div><button class="primary" onclick="showAddRep()">إضافة مندوب جديد</button></div><div class="cards"><div class="card card-blue"><span>الشركات المحتملة</span><strong>${customers.filter(x=>x.status==='شركة محتملة').length}</strong></div><div class="card card-visit visit-card"><span>زيارات اليوم وغدًا</span><div class="mini-visits">${customers.filter(x=>x.nextVisit===today()||x.nextVisit===tomorrow()).map(x=>`<div><b>${x.company}</b><small>${fmt(x.nextVisit)}</small></div>`).join('')||'<small>لا توجد زيارات</small>'}</div></div><div class="card card-purple"><span>تم الشراء</span><strong>${customers.filter(x=>x.status==='تم الشراء').length}</strong></div></div>${visitsBox()}<div class="panel"><h2>المندوبون والعملاء والمتابعات</h2><table><thead><tr><th>المندوب</th><th>العميل</th><th>الشخص المسؤول</th><th>رقم الهاتف</th><th>الحالة</th><th>آخر ملاحظة</th><th>إجراء</th></tr></thead><tbody>${customers.map(r=>`<tr><td>${r.rep}</td><td>${r.company}</td><td>${r.person}</td><td>${r.phone||'—'}</td><td>${statusBadge(r.status)}</td><td class="note">${r.note||'—'}</td><td><button class="ghost" onclick="showHistory('${r.company}','${r.rep}')">سجل المتابعات</button></td></tr>`).join('')}</tbody></table></div>`,'مدير المبيعات')}
function modal(title,fields,submit){app.insertAdjacentHTML('beforeend',`<div class="modal"><div class="modal-box"><h2>${title}</h2>${fields}<div class="actions"><button class="primary" onclick="${submit}">حفظ</button><button class="ghost" onclick="this.closest('.modal').remove()">إلغاء</button></div></div></div>`)}
function showAddCustomer(rep){modal('إضافة عميل جديد',`<label>اسم العميل<input id="cCompany"></label><label>اسم الشخص المسؤول<input id="cPerson"></label><label>رقم الهاتف<input id="cPhone" type="tel"></label>`,`addCustomer('${rep}')`)}
function addCustomer(rep){const company=document.getElementById('cCompany').value.trim(),person=document.getElementById('cPerson').value.trim(),phone=document.getElementById('cPhone').value.trim();if(!company||!person||!phone)return alert('يرجى تعبئة الحقول الثلاثة');const newCustomer={company,person,phone,rep,note:'عميل جديد',status:'شركة محتملة',followDate:today(),nextVisit:'',visits:[]};customers.push(newCustomer);apiPost({action:'addCustomer',...newCustomer});persist();document.querySelector('.modal').remove();enter(rep)}
function showAddFollowup(company,rep){const c=customers.find(x=>x.company===company&&x.rep===rep);modal('إضافة متابعة',`<p class="note">العميل: ${company}</p><div class="follow-types"><button type="button" onclick="pickType(this)">اتصال</button><button type="button" onclick="pickType(this)">واتساب</button><button type="button" onclick="pickType(this)">اجتماع</button><button type="button" onclick="pickType(this)">زيارة</button></div><input type="hidden" id="fType" value="اتصال"><label>تاريخ المتابعة الحالية<input id="fDate" type="date" value="${today()}"></label><label>تاريخ الزيارة القادمة<input id="fNext" type="date"></label><label>حالة العميل<select id="fStatus"><option>شركة محتملة</option><option>تم الاتفاق على الشراء</option><option>تم الشراء</option></select></label><label>ملخص المتابعة<textarea id="fNote"></textarea></label>`,`addFollowup('${company}','${rep}')`)}
function pickType(btn){document.querySelectorAll('.follow-types button').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');document.getElementById('fType').value=btn.textContent}
function addFollowup(company,rep){const note=document.getElementById('fNote').value.trim();if(!note)return alert('اكتب ملخص المتابعة');const c=customers.find(x=>x.company===company&&x.rep===rep);if(c){c.note=note;c.followDate=document.getElementById('fDate').value;c.nextVisit=document.getElementById('fNext').value;c.status=document.getElementById('fStatus').value;c.visits=c.visits||[];c.visits.push({type:document.getElementById('fType').value,date:c.followDate,nextVisit:c.nextVisit,note});apiPost({action:'addFollowup',customerId:c.company,type:document.getElementById('fType').value,followDate:c.followDate,nextVisit:c.nextVisit,note,rep})}persist();document.querySelector('.modal').remove();enter(rep)}
function showHistory(company,rep){const c=customers.find(x=>x.company===company&&x.rep===rep),items=(c&&c.visits)||[];modal('سجل متابعات العميل',`<p class="note">العميل: ${company}</p><table class="history-table"><thead><tr><th>نوع المتابعة</th><th>تاريخ المتابعة</th><th>الزيارة القادمة</th><th>الملاحظة</th></tr></thead><tbody>${items.length?items.map(x=>`<tr><td>${x.type}</td><td>${fmt(x.date)}</td><td>${fmt(x.nextVisit)}</td><td>${x.note}</td></tr>`).join(''):'<tr><td colspan="4">لا توجد متابعات مسجلة</td></tr>'}</tbody></table>`,'')}
function showAddRep(){modal('إضافة مندوب جديد',`<label>اسم المندوب<input id="newRep"></label>`,`addRep()`)}
function addRep(){const n=document.getElementById('newRep').value.trim();if(!n)return alert('اكتب اسم المندوب');if(users.some(x=>x.name===n))return alert('المندوب موجود مسبقًا');users.push({name:n,role:'rep'});persist();document.querySelector('.modal').remove();manager()}
loadData();
