const seedUsers=[{name:'عبدالرحمن',role:'rep'},{name:'سعد',role:'rep'},{name:'خليل',role:'rep'}];
const customers=[['شركة النور التجارية','أحمد السالم','عبدالرحمن','تم التواصل مع العميل','نشط'],['مؤسسة الخليج','خالد العتيبي','سعد','بانتظار تحديد موعد','قيد المتابعة'],['شركة الأفق','سارة أحمد','خليل','تم إرسال العرض','معلق'],['مجموعة المستقبل','عبدالله الزهراني','عبدالرحمن','بانتظار رد العميل','نشط']];
let users=JSON.parse(localStorage.getItem('psh_users')||'null')||seedUsers;let app=document.getElementById('app');
function save(){localStorage.setItem('psh_users',JSON.stringify(users))}
function layout(title,body,user){app.innerHTML=`<div class="shell"><header class="top"><div class="brand">PayScale Hub<small>Sales Tracker</small></div><div class="user">${user||''}</div></header><section class="content">${body}</section></div>`}
function login(){app.innerHTML=`<div class="login"><div class="brand">PayScale Hub<small>Sales Tracker</small></div><h1>اختر المستخدم</h1><p class="note">الدخول إلى متابعة العملاء وفرص المبيعات</p><div class="names">${users.map(u=>`<button class="name" onclick="enter('${u.name}')">${u.name}</button>`).join('')}<button class="name" onclick="managerLogin()">مدير المبيعات</button></div></div>`}
function enter(name){const rows=customers.filter(x=>x[2]===name);layout('',`<div class="hero"><div><h1>صفحة المندوب</h1><p>مرحبًا ${name}، تابع عملاءك ومهامك القادمة.</p></div><button class="primary" onclick="showAdd()">إضافة عميل</button></div><div class="cards"><div class="card"><span>عملائي</span><strong>${rows.length}</strong></div><div class="card"><span>المتابعات القادمة</span><strong>5</strong></div><div class="card"><span>الزيارات هذا الشهر</span><strong>3</strong></div></div><div class="panel"><h2>عملائي</h2><table><thead><tr><th>اسم العميل</th><th>الشخص المسؤول</th><th>آخر ملاحظة</th><th>الحالة</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td class="note">${r[3]}</td><td><span class="status">${r[4]}</span></td></tr>`).join('')}</tbody></table></div>`,name)}
function managerLogin(){app.innerHTML=`<div class="login"><div class="brand">PayScale Hub</div><h1>مدير المبيعات</h1><input id="pass" type="password" placeholder="كلمة المرور" style="padding:12px;border:1px solid var(--line);border-radius:8px;font-family:inherit"><br><br><button class="primary" onclick="checkManager()">دخول</button></div>`}function checkManager(){if(document.getElementById('pass').value==='2026')manager();else alert('كلمة المرور غير صحيحة')}
function manager(){layout('',`<div class="hero"><div><h1>مدير المبيعات</h1><p>متابعة العملاء والفرص لجميع المندوبين.</p></div><button class="primary" onclick="showAddRep()">إضافة مندوب جديد</button></div><div class="cards"><div class="card"><span>إجمالي العملاء</span><strong>${customers.length}</strong></div><div class="card"><span>المتابعات اليوم</span><strong>8</strong></div><div class="card"><span>المندوبون</span><strong>${users.length}</strong></div></div><div class="panel"><h2>المندوبون والعملاء والمتابعات</h2><table><thead><tr><th>المندوب</th><th>العميل</th><th>الشخص المسؤول</th><th>الحالة</th><th>آخر ملاحظة</th></tr></thead><tbody>${customers.map(r=>`<tr><td>${r[2]}</td><td>${r[0]}</td><td>${r[1]}</td><td><span class="status">${r[4]}</span></td><td class="note">${r[3]}</td></tr>`).join('')}</tbody></table></div>`, 'مدير المبيعات')}
function showAdd(){alert('سيتم تفعيل نموذج إضافة العميل في المرحلة التالية.')}
function showAddRep(){app.innerHTML=`<div class="login"><div class="brand">PayScale Hub</div><h1>إضافة مندوب جديد</h1><p class="note">سيتم إنشاء صفحة معيارية له تلقائيًا.</p><input id="newRep" placeholder="اسم المندوب" style="padding:12px;width:100%;border:1px solid var(--line);border-radius:8px;font-family:inherit"><br><br><button class="primary" onclick="addRep()">إنشاء صفحة المندوب</button> <button class="ghost" onclick="manager()">إلغاء</button></div>`}function addRep(){const n=document.getElementById('newRep').value.trim();if(!n)return alert('اكتب اسم المندوب');users.push({name:n,role:'rep'});save();manager();alert('تم إنشاء صفحة معيارية للمندوب '+n)}
login();